CREATE TABLE ACCOUNT (
    Account_ID NUMBER(10) CONSTRAINT PK_ACCOUNT PRIMARY KEY,
    Transaction_ID NUMBER(10) NOT NULL,
    Account_Name VARCHAR2(50) NOT NULL,
	Account_Surname VARCHAR2(50) NOT NULL,
    Account_Balance FLOAT NOT NULL,
    CONSTRAINT FK1_ACCOUNT FOREIGN KEY(Transaction_ID) REFERENCES TRANSACTION(Transaction_ID)
);

CREATE TABLE TRANSACTION (
    Transaction_ID NUMBER(10) CONSTRAINT PK_TRANSACTION PRIMARY KEY,
    Account_ID NUMBER(10) NOT NULL,
    Currency_ID NUMBER(10) NOT NULL,
    Transaction_Amount FLOAT NOT NULL,
    Transaction_Date DATE NOT NULL,
    CONSTRAINT FK1_TRANSACTION FOREIGN KEY(Account_ID) REFERENCES ACCOUNT(Account_ID),
    CONSTRAINT FK2_TRANSACTION FOREIGN KEY(Currency_ID) REFERENCES CURRENCY(Currency_ID)
);

CREATE TABLE CURRENCY (
    Currency_ID NUMBER(10) CONSTRAINT PK_CURRENCY PRIMARY KEY,
    Currency_Type VARCHAR2(50) NOT NULL,
    Currency_Echange_Rate FLOAT(50) NOT NULL,
    Currency_Date DATE
);